### ISSUE TITLE
ai2summarizer

### ISSUE THREAD

**Issue by benzaked** [bxie/ai2_user_trajectory#1]
Hey, I come across your repo when I tried to analyze some data of App Inventor. 
I can see that you used ai2summarizer.py to summarize the scm and bky files. 
Can you please tell me how can I get the summarizer? the link is broken. Thanks!

**Comment by bxie** [comment]
Hi!
I made that repo public again. I'm no longer active in this work, but Prof [Lyn Turbak](https://www.wellesley.edu/cs/faculty/turbak) and his students may still be, so I'd reach out to him. Enjoy!

**Comment by benzaked** [comment]
> Hi!
> I made that repo public again. I'm no longer active in this work, but Prof [Lyn Turbak](https://www.wellesley.edu/cs/faculty/turbak) and his students may still be, so I'd reach out to him. Enjoy!



Thanks a lot! this is very helpful! 
Daniel.
